version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  bot:
    build: .
    container_name: telegram_bot_deeper_systems
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - TELEGRAM_BOT_TOKEN=YOUR_TELEGRAM_BOT_TOKEN
    command: ["python", "telebot.py"]

volumes:
  mongo_data:
